#!/usr/bin/bash                                                                 
                                                                                   
brightness=$(light | grep -Eo '[0-9]{1,3}' | head -1)                              
icon=""                                                                        
                                                                                
echo "<span foreground='#f7f374'>$icon $brightness%</span>" 
