#!/usr/bin/python                                                               
                                                                                   
import requests                                                              
import time                                                    


def get_quote():                      
    """Fetches a random quote from an api server"""              
                                                                                
    url = 'https://api.quotable.io/random'                                
    status_code = None                                                          
                                                                                
    while status_code is None:                                                  
        try:                                                                    
            response = requests.get(url)                                        
                                                                                
            quote = response.json()['content']                                  
            author = response.json()['author']                                  
            status_code = response.status_code                                  
                                                                                
        except requests.exceptions.RequestException:                            
            time.sleep(60)                                                      
                                                                                
                                                                                
    if status_code == 200:
        print(f'<span size="x-small" foreground="#fcba03">{quote}</span><span size="x-small" foreground="#826003"> -- {author}</span>')
    else:                                                                       
        print('Error fetching quote')                                           


get_quote() 
