#!/usr/bin/python                                                                                         

import requests

url = 'https://api.quotable.io/random'
response = requests.get(url)

quote = response.json()['content']
author = response.json()['author']
status_code = response.status_code

if status_code == 200:
    print(f'<span foreground="#fcba03">{quote}</span><span foreground="#826003"> -- {author}</span>')
