#!/usr/bin/bash                                                                                           

# Check if volume is muted
## 0 == not muted and 1 == muted
is_muted=$(pulsemixer --get-mute)

# Get value of volume
volume=`pulsemixer --get-volume | awk '{print $1}'`

if [ $button -eq "3" ]
then
  i3-msg -q exec pavucontrol
  echo " $volume%"
fi

if [ $button -eq "1" ] && [ $is_muted -eq 1 ] 
then
  pulsemixer --unmute
  echo " $volume%"

elif [ $button -eq "1" ] && [ $is_muted -eq 0 ]
then
  pulsemixer --mute
  echo " "

elif [ !$button ] && [ $is_muted -eq 0 ] 
then
  echo " $volume%"

elif [ !$button ] && [ $is_muted -eq 1 ] 
then
  echo " "

fi
