#!/usr/bin/bash                                                                 
                                                                                   
# First check for internet connection                                              
http_status_code=$(curl -Is https://www.google.com | head -1 | grep -Eo '[0-9]{3}*')
                                                                                
while [[ $http_status_code -ne 200 ]];                                          
do                                                                              
  # No internet connection, wait and try again                                  
  sleep 5                                                                       
  # Check for internet connection                                               
  http_status_code=$(curl -Is https://www.google.com | head -1 | grep -Eo '[0-9]{3}*')
done                                                                            
                                                                                
weather=$(curl -s https://wttr.in/Gummersbach?format=1 | tr -d ' ')             
                                                                                
if [[ $button -eq "1" ]]                                                        
then                                                                            
  xfce4-terminal -e "bash -c 'curl https://wttr.in/Gummersbach';bash"           
  echo "$weather"                                                               
else                                                                            
  echo "$weather"                                                               
fi  
