#!/usr/bin/bash                                                                                           

weather=$(curl https://wttr.in/Berlin?format=1 | tr -d ' ')

if [[ $button -eq "1" ]]
then
❘-xfce4-terminal -e "bash -c 'curl https://wttr.in/Berlin';bash"
❘-echo "$weather"
else
❘-echo "$weather"
fi
